hotfix
module.js:340
    throw err;
          ^
Error: Cannot find module '/lib/menu/'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.require.resolve (module.js:384:19)
    at Environment.resolveModulePath (/Users/pascalbrewing/htdocs/cli/mcap-cli/node_modules/yeoman-environment/lib/environment.js:406:18)
    at Environment.register (/Users/pascalbrewing/htdocs/cli/mcap-cli/node_modules/yeoman-environment/lib/environment.js:155:25)
    at /Users/pascalbrewing/htdocs/cli/mcap-cli/cli.js:30:7
    at Environment.resolver.lookup (/Users/pascalbrewing/htdocs/cli/mcap-cli/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at Object.<anonymous> (/Users/pascalbrewing/htdocs/cli/mcap-cli/cli.js:27:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)