fixes error when creating a new project: TypeError: str.substr is not a function
--
encoding was missing, so that content was a Buffer instead of a string.